// Hardcoded Jeopardy board library. Each board = 6 categories x 5 clues.
// `answer` is the accepted response (UI prefixes "What is / Who is").
// cat(title, rows) assigns values 200/400/600/800/1000 in order (easy -> hard).

const VALUES = [200, 400, 600, 800, 1000];
const cat = (title, rows) => ({
  title,
  clues: rows.map(([clue, answer], i) => ({ value: VALUES[i], clue, answer })),
});
const board = (title, categories) => ({ title, categories });

export const BOARDS = [
  board('General Knowledge', [
    cat('World Capitals', [
      ['The capital of France', 'Paris'],
      ['The capital of Japan', 'Tokyo'],
      ['The capital of Australia — no, not Sydney', 'Canberra'],
      ['The capital of Canada', 'Ottawa'],
      ['The capital of Kazakhstan, restored to this name in 2022', 'Astana'],
    ]),
    cat('The Human Body', [
      ['This organ pumps blood through the body', 'Heart'],
      ['The number of bones in the adult human body', '206'],
      ['The largest organ of the human body', 'Skin'],
      ['Red blood cells carry this gas from the lungs to tissues', 'Oxygen'],
      ['The smallest bone in the body, found in the ear', 'Stapes'],
    ]),
    cat('Chemical Elements', [
      ['The element with the symbol O', 'Oxygen'],
      ['The element whose symbol is Au', 'Gold'],
      ['The lightest element on the periodic table', 'Hydrogen'],
      ['First detected in the sun, this element is named for the Greek word for it', 'Helium'],
      ['The only metal that is liquid at room temperature', 'Mercury'],
    ]),
    cat('Inventions', [
      ['Alexander Graham Bell is credited with this device', 'Telephone'],
      ['Thomas Edison developed this practical source of light', 'Light bulb'],
      ['The Wright brothers built the first powered version of this', 'Airplane'],
      ['Tim Berners-Lee invented this in 1989', 'World Wide Web'],
      ['Johannes Gutenberg\'s 15th-century invention', 'Printing press'],
    ]),
    cat('Money', [
      ['The currency of the United States', 'Dollar'],
      ['The currency used across much of Europe', 'Euro'],
      ['The currency of Japan', 'Yen'],
      ['The currency of the United Kingdom', 'Pound'],
      ['The currency of India', 'Rupee'],
    ]),
    cat('Odds & Ends', [
      ['The number of days in a leap year', '366'],
      ['The tallest mountain above sea level', 'Mount Everest'],
      ['The chemical formula H2O refers to this', 'Water'],
      ['The scientific study of weather', 'Meteorology'],
      ['The fear of spiders', 'Arachnophobia'],
    ]),
  ]),

  board('Science & Nature', [
    cat('Physics', [
      ['The force that pulls objects toward Earth', 'Gravity'],
      ['This travels at about 300,000 km per second', 'Light'],
      ['The unit of electrical resistance', 'Ohm'],
      ['In E=mc², energy equals this times the speed of light squared', 'Mass'],
      ['The negatively charged particle orbiting an atom\'s nucleus', 'Electron'],
    ]),
    cat('Biology', [
      ['Often called the powerhouse of the cell', 'Mitochondria'],
      ['The process plants use to make food from sunlight', 'Photosynthesis'],
      ['The molecule that carries genetic information', 'DNA'],
      ['This blood type is the universal donor', 'O negative'],
      ['He proposed evolution by natural selection', 'Charles Darwin'],
    ]),
    cat('Chemistry', [
      ['A solution with a pH below 7 is this', 'Acidic'],
      ['Table salt is sodium and this element', 'Chlorine'],
      ['The most abundant gas in Earth\'s atmosphere', 'Nitrogen'],
      ['When a solid turns directly into a gas', 'Sublimation'],
      ['The horizontal rows of the periodic table', 'Periods'],
    ]),
    cat('Weather', [
      ['Balls of frozen rain that fall in storms', 'Hail'],
      ['A violent rotating column of air touching the ground', 'Tornado'],
      ['The scale that measures hurricane strength', 'Saffir-Simpson'],
      ['The instrument that measures atmospheric pressure', 'Barometer'],
      ['A tropical cyclone in the western Pacific goes by this name', 'Typhoon'],
    ]),
    cat('The Earth', [
      ['The layer of gases surrounding Earth', 'Atmosphere'],
      ['Molten rock beneath Earth\'s surface', 'Magma'],
      ['The supercontinent of 300 million years ago', 'Pangaea'],
      ['The scale historically used for earthquake magnitude', 'Richter'],
      ['The imaginary line at 0 degrees latitude', 'Equator'],
    ]),
    cat('Plants', [
      ['Plants absorb this gas and release oxygen', 'Carbon dioxide'],
      ['The green pigment that captures light in plants', 'Chlorophyll'],
      ['The often colorful part of a flower that attracts pollinators', 'Petal'],
      ['Trees that shed their leaves each year are called this', 'Deciduous'],
      ['The tallest tree species on Earth', 'Coast redwood'],
    ]),
  ]),

  board('World History', [
    cat('Ancient Empires', [
      ['This empire was centered on the city of Rome', 'Roman Empire'],
      ['The pyramids of Giza were built by this civilization', 'Egyptians'],
      ['The vast empire founded by Genghis Khan', 'Mongol Empire'],
      ['Alexander the Great came from this ancient kingdom', 'Macedonia'],
      ['This empire\'s capital was Tenochtitlan', 'Aztec'],
    ]),
    cat('Wars', [
      ['World War II ended in this year', '1945'],
      ['The 1861-1865 war between the American North and South', 'Civil War'],
      ['The 1789 revolution that stormed the Bastille happened here', 'France'],
      ['The Cold War pitted the US against this nation', 'Soviet Union'],
      ['The 1815 battle where Napoleon was finally defeated', 'Waterloo'],
    ]),
    cat('Explorers', [
      ['He sailed west across the Atlantic in 1492', 'Christopher Columbus'],
      ['He led the first expedition to circumnavigate the globe', 'Ferdinand Magellan'],
      ['This explorer reached India by sea in 1498', 'Vasco da Gama'],
      ['First to reach the South Pole, in 1911', 'Roald Amundsen'],
      ['Chinese admiral who led huge treasure fleets in the 1400s', 'Zheng He'],
    ]),
    cat('Leaders', [
      ['The first President of the United States', 'George Washington'],
      ['He led India\'s independence movement through nonviolence', 'Mahatma Gandhi'],
      ['British Prime Minister through most of World War II', 'Winston Churchill'],
      ['The first female Prime Minister of the United Kingdom', 'Margaret Thatcher'],
      ['South African leader imprisoned for 27 years', 'Nelson Mandela'],
    ]),
    cat('Wonders', [
      ['The only ancient wonder still standing', 'Great Pyramid of Giza'],
      ['The Hanging Gardens were said to be in this city', 'Babylon'],
      ['The Colossus stood on this Greek island', 'Rhodes'],
      ['The Great Wall was built to protect this country', 'China'],
      ['The mountaintop citadel Machu Picchu was built by them', 'Inca'],
    ]),
    cat('The 20th Century', [
      ['The ocean liner that sank in 1912', 'Titanic'],
      ['The first person to walk on the moon', 'Neil Armstrong'],
      ['This German city\'s dividing wall fell in 1989', 'Berlin'],
      ['The 1929 event that triggered the Great Depression', 'Stock market crash'],
      ['The 1969 music festival held on a farm in New York', 'Woodstock'],
    ]),
  ]),

  board('Geography', [
    cat('Rivers', [
      ['Traditionally considered the longest river, it flows through Egypt', 'Nile'],
      ['The river that flows through London', 'Thames'],
      ['The Amazon flows mostly through this country', 'Brazil'],
      ['This river forms much of the US-Mexico border', 'Rio Grande'],
      ['Europe\'s longest river', 'Volga'],
    ]),
    cat('Mountains', [
      ['Mount Everest is part of this mountain range', 'Himalayas'],
      ['The highest peak in Africa', 'Kilimanjaro'],
      ['The longest mountain range on land', 'Andes'],
      ['The highest peak in North America', 'Denali'],
      ['These mountains form the border between Europe and Asia', 'Urals'],
    ]),
    cat('Islands', [
      ['The largest island in the world', 'Greenland'],
      ['This island nation lies just south of India', 'Sri Lanka'],
      ['The largest of the Hawaiian islands', 'Hawaii'],
      ['The largest island in the Mediterranean, part of Italy', 'Sicily'],
      ['The 4th-largest island, off Africa\'s southeast coast', 'Madagascar'],
    ]),
    cat('Countries', [
      ['The largest country in the world by area', 'Russia'],
      ['The most populous country in the world', 'India'],
      ['The only country that is also a continent', 'Australia'],
      ['The smallest independent country in the world', 'Vatican City'],
      ['This country is entirely surrounded by South Africa', 'Lesotho'],
    ]),
    cat('US States', [
      ['The largest US state by area', 'Alaska'],
      ['The state nicknamed the Sunshine State', 'Florida'],
      ['This state lies between Lakes Michigan, Huron, and Superior', 'Michigan'],
      ['The only US state that grows coffee commercially', 'Hawaii'],
      ['The Land of 10,000 Lakes', 'Minnesota'],
    ]),
    cat('Oceans & Seas', [
      ['The largest ocean on Earth', 'Pacific'],
      ['The smallest ocean', 'Arctic'],
      ['The sea between Europe and Africa', 'Mediterranean'],
      ['The Dead Sea borders Israel and this country', 'Jordan'],
      ['The deepest known point in the ocean', 'Mariana Trench'],
    ]),
  ]),

  board('At the Movies', [
    cat('Best Picture', [
      ['This 1997 shipwreck epic won 11 Oscars', 'Titanic'],
      ['The first non-English film to win Best Picture, from South Korea', 'Parasite'],
      ['Coppola\'s 1972 mafia epic', 'The Godfather'],
      ['Tom Hanks runs through history in this 1994 film', 'Forrest Gump'],
      ['This 2008 film is set in the slums of Mumbai', 'Slumdog Millionaire'],
    ]),
    cat('Animation', [
      ['Pixar\'s 1995 film about toys that come to life', 'Toy Story'],
      ['Disney film featuring Elsa and "Let It Go"', 'Frozen'],
      ['A lion cub named Simba stars in this Disney classic', 'The Lion King'],
      ['Miyazaki film about a girl working in a spirit bathhouse', 'Spirited Away'],
      ['The 2001 DreamWorks film about a green ogre', 'Shrek'],
    ]),
    cat('Directors', [
      ['He directed Jaws, E.T., and Jurassic Park', 'Steven Spielberg'],
      ['Director of Pulp Fiction and Kill Bill', 'Quentin Tarantino'],
      ['Director of Inception and The Dark Knight', 'Christopher Nolan'],
      ['The "Master of Suspense" who directed Psycho', 'Alfred Hitchcock'],
      ['Director of Do the Right Thing and Malcolm X', 'Spike Lee'],
    ]),
    cat('Sci-Fi', [
      ['"May the Force be with you" comes from this franchise', 'Star Wars'],
      ['The 1999 film with a red pill and a blue pill', 'The Matrix'],
      ['Ridley Scott\'s 1979 space horror film', 'Alien'],
      ['The murderous AI computer in 2001: A Space Odyssey', 'HAL 9000'],
      ['Blade Runner is based on a novel by this author', 'Philip K. Dick'],
    ]),
    cat('Famous Lines', [
      ['This actor\'s character growls "I\'ll be back"', 'Arnold Schwarzenegger'],
      ['"Here\'s looking at you, kid" is from this 1942 film', 'Casablanca'],
      ['"You can\'t handle the truth!" is shouted in this film', 'A Few Good Men'],
      ['"Frankly, my dear, I don\'t give a damn" ends this 1939 film', 'Gone with the Wind'],
      ['"I\'m gonna make him an offer he can\'t refuse" is from this film', 'The Godfather'],
    ]),
    cat('Actors', [
      ['He played Jack in Titanic', 'Leonardo DiCaprio'],
      ['She played Hermione Granger in the Harry Potter films', 'Emma Watson'],
      ['He played Iron Man in the Marvel films', 'Robert Downey Jr.'],
      ['The actress with the most Oscar acting nominations', 'Meryl Streep'],
      ['He won an Oscar for playing the Joker in 2019', 'Joaquin Phoenix'],
    ]),
  ]),

  board('Music', [
    cat('Rock Legends', [
      ['The band behind "Bohemian Rhapsody"', 'Queen'],
      ['The Beatles formed in this English city', 'Liverpool'],
      ['Guitarist famous for "Purple Haze"', 'Jimi Hendrix'],
      ['The band behind "Stairway to Heaven"', 'Led Zeppelin'],
      ['The New Jersey rocker nicknamed "The Boss"', 'Bruce Springsteen'],
    ]),
    cat('Pop Icons', [
      ['The "King of Pop"', 'Michael Jackson'],
      ['She sang "Shake It Off" and "Anti-Hero"', 'Taylor Swift'],
      ['The "Queen of Pop" who sang "Like a Prayer"', 'Madonna'],
      ['Barbadian singer of "Umbrella"', 'Rihanna'],
      ['British singer of "Rolling in the Deep"', 'Adele'],
    ]),
    cat('Instruments', [
      ['This keyboard instrument has 88 keys', 'Piano'],
      ['A brass instrument played with a slide', 'Trombone'],
      ['The largest string instrument in an orchestra', 'Double bass'],
      ['This double-reed woodwind tunes the orchestra', 'Oboe'],
      ['The instrument Yo-Yo Ma is famous for playing', 'Cello'],
    ]),
    cat('Genres', [
      ['The Jamaican genre made famous by Bob Marley', 'Reggae'],
      ['This improvisational genre was born in New Orleans', 'Jazz'],
      ['The fast, raw genre associated with mosh pits', 'Punk'],
      ['"R&B" stands for rhythm and this', 'Blues'],
      ['"EDM" stands for electronic ___ music', 'Dance'],
    ]),
    cat('Classical', [
      ['He composed his Ninth Symphony while deaf', 'Beethoven'],
      ['Child prodigy who wrote "Eine kleine Nachtmusik"', 'Mozart'],
      ['Italian composer of "The Four Seasons"', 'Vivaldi'],
      ['Russian composer of "The Nutcracker"', 'Tchaikovsky'],
      ['Composer of the "Brandenburg Concertos"', 'Bach'],
    ]),
    cat('Number Ones', [
      ['The band behind "Hey Jude"', 'The Beatles'],
      ['Luis Fonsi\'s 2017 smash featuring Daddy Yankee', 'Despacito'],
      ['Ed Sheeran\'s 2017 hit named for a form', 'Shape of You'],
      ['The best-selling single of all time, a Bing Crosby classic', 'White Christmas'],
      ['PSY\'s 2012 viral hit', 'Gangnam Style'],
    ]),
  ]),

  board('Sports', [
    cat('The Beautiful Game', [
      ['The number of players per side on a soccer field', '11'],
      ['The trophy contested every four years by national teams', 'World Cup'],
      ['Argentine star who lifted the 2022 World Cup', 'Lionel Messi'],
      ['The country that has won the most World Cups', 'Brazil'],
      ['The English club known as the "Red Devils"', 'Manchester United'],
    ]),
    cat('Basketball', [
      ['The number of points for a shot beyond the arc', '3'],
      ['Michael Jordan won six titles with this team', 'Chicago Bulls'],
      ['The top professional basketball league in the US', 'NBA'],
      ['The player nicknamed "King James"', 'LeBron James'],
      ['This franchise shares the record for most NBA titles', 'Boston Celtics'],
    ]),
    cat('The Olympics', [
      ['The Summer Games are held every this many years', '4'],
      ['The number of interlocking rings on the Olympic flag', '5'],
      ['This city hosted the 2024 Summer Olympics', 'Paris'],
      ['The swimmer with the most Olympic gold medals', 'Michael Phelps'],
      ['The ancient Olympics were held in this country', 'Greece'],
    ]),
    cat('Tennis', [
      ['The Grand Slam played on grass in London', 'Wimbledon'],
      ['A score of zero in tennis is called this', 'Love'],
      ['Serena Williams\'s older sister and rival', 'Venus Williams'],
      ['Swiss great with 20 Grand Slam titles', 'Roger Federer'],
      ['The clay-court Grand Slam held in Paris', 'French Open'],
    ]),
    cat('Baseball', [
      ['The number of strikes that make an out', '3'],
      ['A home run hit with the bases loaded', 'Grand slam'],
      ['Major League Baseball\'s championship series', 'World Series'],
      ['He broke baseball\'s color barrier in 1947', 'Jackie Robinson'],
      ['The Yankees slugger known as the "Sultan of Swat"', 'Babe Ruth'],
    ]),
    cat('Mixed Bag', [
      ['The sport played at Augusta National in the Masters', 'Golf'],
      ['The Jamaican sprinter called the fastest man alive', 'Usain Bolt'],
      ['Boxing legend who said "float like a butterfly"', 'Muhammad Ali'],
      ['British F1 driver with seven world titles', 'Lewis Hamilton'],
      ['The American gymnast with the most World medals', 'Simone Biles'],
    ]),
  ]),

  board('Video Games', [
    cat('Nintendo', [
      ['The mustachioed plumber who is Nintendo\'s mascot', 'Mario'],
      ['Mario\'s friendly green dinosaur companion', 'Yoshi'],
      ['The elf-like hero of The Legend of Zelda', 'Link'],
      ['The yellow electric mascot of Pokemon', 'Pikachu'],
      ['The pink puffball who inhales his enemies', 'Kirby'],
    ]),
    cat('Consoles', [
      ['Sony\'s console line, currently on its fifth model', 'PlayStation'],
      ['Microsoft\'s home console brand', 'Xbox'],
      ['Nintendo\'s 2017 handheld-console hybrid', 'Switch'],
      ['Sega\'s 16-bit console, called the Genesis in the US', 'Genesis'],
      ['The best-selling home console of all time', 'PlayStation 2'],
    ]),
    cat('Blockbusters', [
      ['The block-building sandbox game by Mojang', 'Minecraft'],
      ['Epic\'s battle royale famous for building and dances', 'Fortnite'],
      ['Rockstar\'s open-world crime series, abbreviated GTA', 'Grand Theft Auto'],
      ['The 2017 open-world Zelda subtitled "Breath of the ___"', 'Wild'],
      ['Capcom\'s long-running survival horror franchise', 'Resident Evil'],
    ]),
    cat('Retro', [
      ['The arcade game with a yellow character eating pellets', 'Pac-Man'],
      ['The falling-blocks puzzle game from the Soviet Union', 'Tetris'],
      ['The ape who hurls barrels at Mario', 'Donkey Kong'],
      ['The 1972 Atari game that simulates table tennis', 'Pong'],
      ['The 1978 arcade shooter about defending Earth from aliens', 'Space Invaders'],
    ]),
    cat('Characters', [
      ['Sega\'s blue, super-fast hedgehog', 'Sonic'],
      ['Treasure hunter Lara Croft stars in this series', 'Tomb Raider'],
      ['The green-armored Master Chief leads this series', 'Halo'],
      ['Mario\'s spiky-shelled archenemy', 'Bowser'],
      ['The Spartan warrior hero of God of War', 'Kratos'],
    ]),
    cat('Esports', [
      ['Riot\'s hit MOBA, "League of ___"', 'Legends'],
      ['Valve\'s tactical shooter series, "Counter-___"', 'Strike'],
      ['Valve\'s MOBA with an annual tournament called The International', 'Dota 2'],
      ['Riot\'s 2020 tactical shooter', 'Valorant'],
      ['Respawn\'s battle royale set in the Titanfall universe', 'Apex Legends'],
    ]),
  ]),

  board('Literature', [
    cat('Shakespeare', [
      ['The young lovers of fair Verona', 'Romeo and Juliet'],
      ['The Danish prince who ponders "To be or not to be"', 'Hamlet'],
      ['The Scottish play about a murderous king', 'Macbeth'],
      ['The Moor of Venice deceived by Iago', 'Othello'],
      ['The London theatre most associated with Shakespeare', 'The Globe'],
    ]),
    cat('Classic Novels', [
      ['Herman Melville\'s novel about a white whale', 'Moby-Dick'],
      ['Jane Austen novel featuring Elizabeth Bennet and Mr. Darcy', 'Pride and Prejudice'],
      ['George Orwell\'s dystopia ruled by Big Brother', '1984'],
      ['F. Scott Fitzgerald\'s novel about Jay Gatsby', 'The Great Gatsby'],
      ['Tolstoy\'s epic novel of Russia and Napoleon', 'War and Peace'],
    ]),
    cat('Kids\' Books', [
      ['The boy wizard created by J.K. Rowling', 'Harry Potter'],
      ['Author of "The Very Hungry Caterpillar"', 'Eric Carle'],
      ['Tolkien novel in which Bilbo Baggins finds a ring', 'The Hobbit'],
      ['In the Narnia title, "The Lion, the Witch and the ___"', 'Wardrobe'],
      ['Pen name of the author of "The Cat in the Hat"', 'Dr. Seuss'],
    ]),
    cat('Poets', [
      ['Author of the poem "The Raven"', 'Edgar Allan Poe'],
      ['"The Road Not Taken" was written by this American poet', 'Robert Frost'],
      ['American poet of "Leaves of Grass"', 'Walt Whitman'],
      ['The reclusive poet from Amherst, Massachusetts', 'Emily Dickinson'],
      ['Chilean Nobel poet who wrote love sonnets', 'Pablo Neruda'],
    ]),
    cat('Detectives', [
      ['Arthur Conan Doyle\'s pipe-smoking sleuth', 'Sherlock Holmes'],
      ['Agatha Christie\'s mustachioed Belgian detective', 'Hercule Poirot'],
      ['Christie\'s elderly amateur sleuth from St. Mary Mead', 'Miss Marple'],
      ['Raymond Chandler\'s hard-boiled detective', 'Philip Marlowe'],
      ['Sherlock Holmes\'s loyal doctor friend', 'Dr. Watson'],
    ]),
    cat('First Lines', [
      ['"Call me Ishmael" opens this novel', 'Moby-Dick'],
      ['"It was the best of times..." begins this Dickens novel', 'A Tale of Two Cities'],
      ['"...the clocks were striking thirteen" opens this novel', '1984'],
      ['"Happy families are all alike..." opens this Tolstoy novel', 'Anna Karenina'],
      ['"In a hole in the ground there lived a ___"', 'Hobbit'],
    ]),
  ]),

  board('Food & Drink', [
    cat('Cuisines', [
      ['Pizza and pasta originated in this country', 'Italy'],
      ['Sushi and ramen come from this country', 'Japan'],
      ['Tacos and enchiladas come from this country', 'Mexico'],
      ['Curry and naan are strongly associated with this country', 'India'],
      ['Croissants and baguettes come from this country', 'France'],
    ]),
    cat('Fruits & Veg', [
      ['A long, yellow, curved fruit', 'Banana'],
      ['The fruit said to keep the doctor away', 'Apple'],
      ['The orange root vegetable said to help eyesight', 'Carrot'],
      ['The fruit fermented to make wine', 'Grape'],
      ['The green fruit that is the base of guacamole', 'Avocado'],
    ]),
    cat('In the Kitchen', [
      ['The appliance you bake bread and cakes in', 'Oven'],
      ['A chef\'s tall, pleated white hat', 'Toque'],
      ['Cooking food by submerging it in hot oil', 'Frying'],
      ['Pasta cooked "al ___" is firm to the bite', 'Dente'],
      ['The French mother sauce of butter, flour, and milk', 'Bechamel'],
    ]),
    cat('Drinks', [
      ['The world\'s most popular drink after water', 'Tea'],
      ['The beverage brewed from roasted beans', 'Coffee'],
      ['True Champagne comes only from this region of France', 'Champagne'],
      ['The Japanese rice wine', 'Sake'],
      ['The agave-based spirit from Mexico', 'Tequila'],
    ]),
    cat('Desserts', [
      ['The frozen dairy treat often served in a cone', 'Ice cream'],
      ['The Italian frozen dessert, denser than ice cream', 'Gelato'],
      ['The Italian layered dessert flavored with coffee', 'Tiramisu'],
      ['The French custard topped with hard caramelized sugar', 'Creme brulee'],
      ['The Austrian pastry made with thin dough and apples', 'Strudel'],
    ]),
    cat('Spices', [
      ['This pepper-derived spice makes food hot', 'Chili'],
      ['This spice from tree bark flavors rolls and lattes', 'Cinnamon'],
      ['The world\'s most expensive spice by weight', 'Saffron'],
      ['The spice that gives curry powder its yellow color', 'Turmeric'],
      ['The fragrant pods used in chai and Indian sweets', 'Cardamom'],
    ]),
  ]),

  board('Space & Astronomy', [
    cat('The Solar System', [
      ['The star at the center of our solar system', 'Sun'],
      ['The planet we live on', 'Earth'],
      ['The largest planet in the solar system', 'Jupiter'],
      ['The planet best known for its spectacular rings', 'Saturn'],
      ['The dwarf planet reclassified in 2006', 'Pluto'],
    ]),
    cat('The Moon', [
      ['The number of natural moons Earth has', '1'],
      ['The first person to walk on the moon', 'Neil Armstrong'],
      ['The NASA program that first landed humans on the moon', 'Apollo'],
      ['The moon\'s dark plains are "maria," Latin for this', 'Seas'],
      ['The moon\'s gravity is the main cause of these ocean movements', 'Tides'],
    ]),
    cat('Stars & Galaxies', [
      ['Our galaxy is called the ___ Way', 'Milky'],
      ['The violent explosion of a dying massive star', 'Supernova'],
      ['The closest star to the Sun', 'Proxima Centauri'],
      ['A region where gravity is so strong not even light escapes', 'Black hole'],
      ['The constellation depicting a hunter with a famous belt', 'Orion'],
    ]),
    cat('Exploration', [
      ['The US space agency', 'NASA'],
      ['NASA\'s reusable spacecraft retired in 2011', 'Space Shuttle'],
      ['The first artificial satellite, launched by the USSR', 'Sputnik'],
      ['The space telescope launched in 1990', 'Hubble'],
      ['The NASA rover that landed on Mars in 2021', 'Perseverance'],
    ]),
    cat('The Planets', [
      ['The "Red Planet"', 'Mars'],
      ['The planet closest to the Sun', 'Mercury'],
      ['The hottest planet in the solar system', 'Venus'],
      ['The planet that rotates tipped on its side', 'Uranus'],
      ['The farthest major planet from the Sun', 'Neptune'],
    ]),
    cat('Cosmic Terms', [
      ['The leading theory of the universe\'s origin, the "Big ___"', 'Bang'],
      ['A rocky body orbiting the Sun, many between Mars and Jupiter', 'Asteroid'],
      ['A "shooting star" streaking through the atmosphere', 'Meteor'],
      ['An icy body with a glowing tail, like Halley\'s', 'Comet'],
      ['The force that keeps planets in orbit around the Sun', 'Gravity'],
    ]),
  ]),

  board('Animals', [
    cat('Mammals', [
      ['The largest living land animal', 'Elephant'],
      ['The tallest animal in the world', 'Giraffe'],
      ['The fastest land animal', 'Cheetah'],
      ['The only mammals capable of true flight', 'Bats'],
      ['The largest animal that has ever lived', 'Blue whale'],
    ]),
    cat('Birds', [
      ['The flightless bird that lays the largest egg', 'Ostrich'],
      ['The national bird of the United States', 'Bald eagle'],
      ['The colorful bird famous for mimicking human speech', 'Parrot'],
      ['The flightless Antarctic bird that swims', 'Penguin'],
      ['The only bird that can fly backward', 'Hummingbird'],
    ]),
    cat('Ocean Life', [
      ['The largest fish, a gentle filter feeder', 'Whale shark'],
      ['The eight-armed sea creature', 'Octopus'],
      ['The toothy predator that terrorized swimmers in "Jaws"', 'Shark'],
      ['The intelligent marine mammal that uses echolocation', 'Dolphin'],
      ['The five-armed sea creature that can regrow lost arms', 'Starfish'],
    ]),
    cat('Bugs', [
      ['The insect that makes honey', 'Bee'],
      ['The winged insect a caterpillar transforms into', 'Butterfly'],
      ['These social insects build hills and march in lines', 'Ants'],
      ['The beetle that glows in the dark on summer nights', 'Firefly'],
      ['The loud summer insect that emerges in broods', 'Cicada'],
    ]),
    cat('Reptiles', [
      ['The reptile that carries a protective shell', 'Turtle'],
      ['The lizard famous for changing color', 'Chameleon'],
      ['The largest living reptile', 'Saltwater crocodile'],
      ['The venomous snake that spreads a hood when threatened', 'Cobra'],
      ['The largest lizard, native to Indonesia', 'Komodo dragon'],
    ]),
    cat('Animal Groups', [
      ['A group of lions', 'Pride'],
      ['A group of wolves', 'Pack'],
      ['A group of crows', 'Murder'],
      ['A group of fish', 'School'],
      ['A group of geese flying in formation', 'Skein'],
    ]),
  ]),
];
