// Hardcoded Jeopardy board library. Each board = 6 categories x 5 clues.
// `answer` is the accepted response (UI prefixes "What is / Who is").
// cat(title, rows) assigns values 200/400/600/800/1000 in order (easy -> hard).

const VALUES = [200, 400, 600, 800, 1000];
const cat = (title, rows) => ({
  title,
  clues: rows.map(([clue, answer], i) => ({ value: VALUES[i], clue, answer })),
});
const board = (title, categories) => ({ title, categories });

export const BOARDS = [
  board('General Knowledge', [
    cat('World Capitals', [
      ['The capital of France', 'Paris'],
      ['The capital of Japan', 'Tokyo'],
      ['The capital of Australia — no, not Sydney', 'Canberra'],
      ['The capital of Canada', 'Ottawa'],
      ['The capital of Kazakhstan, restored to this name in 2022', 'Astana'],
    ]),
    cat('The Human Body', [
      ['This organ pumps blood through the body', 'Heart'],
      ['The number of bones in the adult human body', '206'],
      ['The largest organ of the human body', 'Skin'],
      ['Red blood cells carry this gas from the lungs to tissues', 'Oxygen'],
      ['The smallest bone in the body, found in the ear', 'Stapes'],
    ]),
    cat('Chemical Elements', [
      ['The element with the symbol O', 'Oxygen'],
      ['The element whose symbol is Au', 'Gold'],
      ['The lightest element on the periodic table', 'Hydrogen'],
      ['First detected in the sun, this element is named for the Greek word for it', 'Helium'],
      ['The only metal that is liquid at room temperature', 'Mercury'],
    ]),
    cat('Inventions', [
      ['Alexander Graham Bell is credited with this device', 'Telephone'],
      ['Thomas Edison developed this practical source of light', 'Light bulb'],
      ['The Wright brothers built the first powered version of this', 'Airplane'],
      ['Tim Berners-Lee invented this in 1989', 'World Wide Web'],
      ['Johannes Gutenberg\'s 15th-century invention', 'Printing press'],
    ]),
    cat('Money', [
      ['The currency of the United States', 'Dollar'],
      ['The currency used across much of Europe', 'Euro'],
      ['The currency of Japan', 'Yen'],
      ['The currency of the United Kingdom', 'Pound'],
      ['The currency of India', 'Rupee'],
    ]),
    cat('Odds & Ends', [
      ['The number of days in a leap year', '366'],
      ['The tallest mountain above sea level', 'Mount Everest'],
      ['The chemical formula H2O refers to this', 'Water'],
      ['The scientific study of weather', 'Meteorology'],
      ['The fear of spiders', 'Arachnophobia'],
    ]),
  ]),

  board('Science & Nature', [
    cat('Physics', [
      ['The force that pulls objects toward Earth', 'Gravity'],
      ['This travels at about 300,000 km per second', 'Light'],
      ['The unit of electrical resistance', 'Ohm'],
      ['In E=mc², energy equals this times the speed of light squared', 'Mass'],
      ['The negatively charged particle orbiting an atom\'s nucleus', 'Electron'],
    ]),
    cat('Biology', [
      ['Often called the powerhouse of the cell', 'Mitochondria'],
      ['The process plants use to make food from sunlight', 'Photosynthesis'],
      ['The molecule that carries genetic information', 'DNA'],
      ['This blood type is the universal donor', 'O negative'],
      ['He proposed evolution by natural selection', 'Charles Darwin'],
    ]),
    cat('Chemistry', [
      ['A solution with a pH below 7 is this', 'Acidic'],
      ['Table salt is sodium and this element', 'Chlorine'],
      ['The most abundant gas in Earth\'s atmosphere', 'Nitrogen'],
      ['When a solid turns directly into a gas', 'Sublimation'],
      ['The horizontal rows of the periodic table', 'Periods'],
    ]),
    cat('Weather', [
      ['Balls of frozen rain that fall in storms', 'Hail'],
      ['A violent rotating column of air touching the ground', 'Tornado'],
      ['The scale that measures hurricane strength', 'Saffir-Simpson'],
      ['The instrument that measures atmospheric pressure', 'Barometer'],
      ['A tropical cyclone in the western Pacific goes by this name', 'Typhoon'],
    ]),
    cat('The Earth', [
      ['The layer of gases surrounding Earth', 'Atmosphere'],
      ['Molten rock beneath Earth\'s surface', 'Magma'],
      ['The supercontinent of 300 million years ago', 'Pangaea'],
      ['The scale historically used for earthquake magnitude', 'Richter'],
      ['The imaginary line at 0 degrees latitude', 'Equator'],
    ]),
    cat('Plants', [
      ['Plants absorb this gas and release oxygen', 'Carbon dioxide'],
      ['The green pigment that captures light in plants', 'Chlorophyll'],
      ['The often colorful part of a flower that attracts pollinators', 'Petal'],
      ['Trees that shed their leaves each year are called this', 'Deciduous'],
      ['The tallest tree species on Earth', 'Coast redwood'],
    ]),
  ]),

  board('World History', [
    cat('Ancient Empires', [
      ['This empire was centered on the city of Rome', 'Roman Empire'],
      ['The pyramids of Giza were built by this civilization', 'Egyptians'],
      ['The vast empire founded by Genghis Khan', 'Mongol Empire'],
      ['Alexander the Great came from this ancient kingdom', 'Macedonia'],
      ['This empire\'s capital was Tenochtitlan', 'Aztec'],
    ]),
    cat('Wars', [
      ['World War II ended in this year', '1945'],
      ['The 1861-1865 war between the American North and South', 'Civil War'],
      ['The 1789 revolution that stormed the Bastille happened here', 'France'],
      ['The Cold War pitted the US against this nation', 'Soviet Union'],
      ['The 1815 battle where Napoleon was finally defeated', 'Waterloo'],
    ]),
    cat('Explorers', [
      ['He sailed west across the Atlantic in 1492', 'Christopher Columbus'],
      ['He led the first expedition to circumnavigate the globe', 'Ferdinand Magellan'],
      ['This explorer reached India by sea in 1498', 'Vasco da Gama'],
      ['First to reach the South Pole, in 1911', 'Roald Amundsen'],
      ['Chinese admiral who led huge treasure fleets in the 1400s', 'Zheng He'],
    ]),
    cat('Leaders', [
      ['The first President of the United States', 'George Washington'],
      ['He led India\'s independence movement through nonviolence', 'Mahatma Gandhi'],
      ['British Prime Minister through most of World War II', 'Winston Churchill'],
      ['The first female Prime Minister of the United Kingdom', 'Margaret Thatcher'],
      ['South African leader imprisoned for 27 years', 'Nelson Mandela'],
    ]),
    cat('Wonders', [
      ['The only ancient wonder still standing', 'Great Pyramid of Giza'],
      ['The Hanging Gardens were said to be in this city', 'Babylon'],
      ['The Colossus stood on this Greek island', 'Rhodes'],
      ['The Great Wall was built to protect this country', 'China'],
      ['The mountaintop citadel Machu Picchu was built by them', 'Inca'],
    ]),
    cat('The 20th Century', [
      ['The ocean liner that sank in 1912', 'Titanic'],
      ['The first person to walk on the moon', 'Neil Armstrong'],
      ['This German city\'s dividing wall fell in 1989', 'Berlin'],
      ['The 1929 event that triggered the Great Depression', 'Stock market crash'],
      ['The 1969 music festival held on a farm in New York', 'Woodstock'],
    ]),
  ]),

  board('Geography', [
    cat('Rivers', [
      ['Traditionally considered the longest river, it flows through Egypt', 'Nile'],
      ['The river that flows through London', 'Thames'],
      ['The Amazon flows mostly through this country', 'Brazil'],
      ['This river forms much of the US-Mexico border', 'Rio Grande'],
      ['Europe\'s longest river', 'Volga'],
    ]),
    cat('Mountains', [
      ['Mount Everest is part of this mountain range', 'Himalayas'],
      ['The highest peak in Africa', 'Kilimanjaro'],
      ['The longest mountain range on land', 'Andes'],
      ['The highest peak in North America', 'Denali'],
      ['These mountains form the border between Europe and Asia', 'Urals'],
    ]),
    cat('Islands', [
      ['The largest island in the world', 'Greenland'],
      ['This island nation lies just south of India', 'Sri Lanka'],
      ['The largest of the Hawaiian islands', 'Hawaii'],
      ['The largest island in the Mediterranean, part of Italy', 'Sicily'],
      ['The 4th-largest island, off Africa\'s southeast coast', 'Madagascar'],
    ]),
    cat('Countries', [
      ['The largest country in the world by area', 'Russia'],
      ['The most populous country in the world', 'India'],
      ['The only country that is also a continent', 'Australia'],
      ['The smallest independent country in the world', 'Vatican City'],
      ['This country is entirely surrounded by South Africa', 'Lesotho'],
    ]),
    cat('US States', [
      ['The largest US state by area', 'Alaska'],
      ['The state nicknamed the Sunshine State', 'Florida'],
      ['This state lies between Lakes Michigan, Huron, and Superior', 'Michigan'],
      ['The only US state that grows coffee commercially', 'Hawaii'],
      ['The Land of 10,000 Lakes', 'Minnesota'],
    ]),
    cat('Oceans & Seas', [
      ['The largest ocean on Earth', 'Pacific'],
      ['The smallest ocean', 'Arctic'],
      ['The sea between Europe and Africa', 'Mediterranean'],
      ['The Dead Sea borders Israel and this country', 'Jordan'],
      ['The deepest known point in the ocean', 'Mariana Trench'],
    ]),
  ]),

  board('At the Movies', [
    cat('Best Picture', [
      ['This 1997 shipwreck epic won 11 Oscars', 'Titanic'],
      ['The first non-English film to win Best Picture, from South Korea', 'Parasite'],
      ['Coppola\'s 1972 mafia epic', 'The Godfather'],
      ['Tom Hanks runs through history in this 1994 film', 'Forrest Gump'],
      ['This 2008 film is set in the slums of Mumbai', 'Slumdog Millionaire'],
    ]),
    cat('Animation', [
      ['Pixar\'s 1995 film about toys that come to life', 'Toy Story'],
      ['Disney film featuring Elsa and "Let It Go"', 'Frozen'],
      ['A lion cub named Simba stars in this Disney classic', 'The Lion King'],
      ['Miyazaki film about a girl working in a spirit bathhouse', 'Spirited Away'],
      ['The 2001 DreamWorks film about a green ogre', 'Shrek'],
    ]),
    cat('Directors', [
      ['He directed Jaws, E.T., and Jurassic Park', 'Steven Spielberg'],
      ['Director of Pulp Fiction and Kill Bill', 'Quentin Tarantino'],
      ['Director of Inception and The Dark Knight', 'Christopher Nolan'],
      ['The "Master of Suspense" who directed Psycho', 'Alfred Hitchcock'],
      ['Director of Do the Right Thing and Malcolm X', 'Spike Lee'],
    ]),
    cat('Sci-Fi', [
      ['"May the Force be with you" comes from this franchise', 'Star Wars'],
      ['The 1999 film with a red pill and a blue pill', 'The Matrix'],
      ['Ridley Scott\'s 1979 space horror film', 'Alien'],
      ['The murderous AI computer in 2001: A Space Odyssey', 'HAL 9000'],
      ['Blade Runner is based on a novel by this author', 'Philip K. Dick'],
    ]),
    cat('Famous Lines', [
      ['This actor\'s character growls "I\'ll be back"', 'Arnold Schwarzenegger'],
      ['"Here\'s looking at you, kid" is from this 1942 film', 'Casablanca'],
      ['"You can\'t handle the truth!" is shouted in this film', 'A Few Good Men'],
      ['"Frankly, my dear, I don\'t give a damn" ends this 1939 film', 'Gone with the Wind'],
      ['"I\'m gonna make him an offer he can\'t refuse" is from this film', 'The Godfather'],
    ]),
    cat('Actors', [
      ['He played Jack in Titanic', 'Leonardo DiCaprio'],
      ['She played Hermione Granger in the Harry Potter films', 'Emma Watson'],
      ['He played Iron Man in the Marvel films', 'Robert Downey Jr.'],
      ['The actress with the most Oscar acting nominations', 'Meryl Streep'],
      ['He won an Oscar for playing the Joker in 2019', 'Joaquin Phoenix'],
    ]),
  ]),

  board('Music', [
    cat('Rock Legends', [
      ['The band behind "Bohemian Rhapsody"', 'Queen'],
      ['The Beatles formed in this English city', 'Liverpool'],
      ['Guitarist famous for "Purple Haze"', 'Jimi Hendrix'],
      ['The band behind "Stairway to Heaven"', 'Led Zeppelin'],
      ['The New Jersey rocker nicknamed "The Boss"', 'Bruce Springsteen'],
    ]),
    cat('Pop Icons', [
      ['The "King of Pop"', 'Michael Jackson'],
      ['She sang "Shake It Off" and "Anti-Hero"', 'Taylor Swift'],
      ['The "Queen of Pop" who sang "Like a Prayer"', 'Madonna'],
      ['Barbadian singer of "Umbrella"', 'Rihanna'],
      ['British singer of "Rolling in the Deep"', 'Adele'],
    ]),
    cat('Instruments', [
      ['This keyboard instrument has 88 keys', 'Piano'],
      ['A brass instrument played with a slide', 'Trombone'],
      ['The largest string instrument in an orchestra', 'Double bass'],
      ['This double-reed woodwind tunes the orchestra', 'Oboe'],
      ['The instrument Yo-Yo Ma is famous for playing', 'Cello'],
    ]),
    cat('Genres', [
      ['The Jamaican genre made famous by Bob Marley', 'Reggae'],
      ['This improvisational genre was born in New Orleans', 'Jazz'],
      ['The fast, raw genre associated with mosh pits', 'Punk'],
      ['"R&B" stands for rhythm and this', 'Blues'],
      ['"EDM" stands for electronic ___ music', 'Dance'],
    ]),
    cat('Classical', [
      ['He composed his Ninth Symphony while deaf', 'Beethoven'],
      ['Child prodigy who wrote "Eine kleine Nachtmusik"', 'Mozart'],
      ['Italian composer of "The Four Seasons"', 'Vivaldi'],
      ['Russian composer of "The Nutcracker"', 'Tchaikovsky'],
      ['Composer of the "Brandenburg Concertos"', 'Bach'],
    ]),
    cat('Number Ones', [
      ['The band behind "Hey Jude"', 'The Beatles'],
      ['Luis Fonsi\'s 2017 smash featuring Daddy Yankee', 'Despacito'],
      ['Ed Sheeran\'s 2017 hit named for a form', 'Shape of You'],
      ['The best-selling single of all time, a Bing Crosby classic', 'White Christmas'],
      ['PSY\'s 2012 viral hit', 'Gangnam Style'],
    ]),
  ]),

  board('Sports', [
    cat('The Beautiful Game', [
      ['The number of players per side on a soccer field', '11'],
      ['The trophy contested every four years by national teams', 'World Cup'],
      ['Argentine star who lifted the 2022 World Cup', 'Lionel Messi'],
      ['The country that has won the most World Cups', 'Brazil'],
      ['The English club known as the "Red Devils"', 'Manchester United'],
    ]),
    cat('Basketball', [
      ['The number of points for a shot beyond the arc', '3'],
      ['Michael Jordan won six titles with this team', 'Chicago Bulls'],
      ['The top professional basketball league in the US', 'NBA'],
      ['The player nicknamed "King James"', 'LeBron James'],
      ['This franchise shares the record for most NBA titles', 'Boston Celtics'],
    ]),
    cat('The Olympics', [
      ['The Summer Games are held every this many years', '4'],
      ['The number of interlocking rings on the Olympic flag', '5'],
      ['This city hosted the 2024 Summer Olympics', 'Paris'],
      ['The swimmer with the most Olympic gold medals', 'Michael Phelps'],
      ['The ancient Olympics were held in this country', 'Greece'],
    ]),
    cat('Tennis', [
      ['The Grand Slam played on grass in London', 'Wimbledon'],
      ['A score of zero in tennis is called this', 'Love'],
      ['Serena Williams\'s older sister and rival', 'Venus Williams'],
      ['Swiss great with 20 Grand Slam titles', 'Roger Federer'],
      ['The clay-court Grand Slam held in Paris', 'French Open'],
    ]),
    cat('Baseball', [
      ['The number of strikes that make an out', '3'],
      ['A home run hit with the bases loaded', 'Grand slam'],
      ['Major League Baseball\'s championship series', 'World Series'],
      ['He broke baseball\'s color barrier in 1947', 'Jackie Robinson'],
      ['The Yankees slugger known as the "Sultan of Swat"', 'Babe Ruth'],
    ]),
    cat('Mixed Bag', [
      ['The sport played at Augusta National in the Masters', 'Golf'],
      ['The Jamaican sprinter called the fastest man alive', 'Usain Bolt'],
      ['Boxing legend who said "float like a butterfly"', 'Muhammad Ali'],
      ['British F1 driver with seven world titles', 'Lewis Hamilton'],
      ['The American gymnast with the most World medals', 'Simone Biles'],
    ]),
  ]),

  board('Video Games', [
    cat('Nintendo', [
      ['The mustachioed plumber who is Nintendo\'s mascot', 'Mario'],
      ['Mario\'s friendly green dinosaur companion', 'Yoshi'],
      ['The elf-like hero of The Legend of Zelda', 'Link'],
      ['The yellow electric mascot of Pokemon', 'Pikachu'],
      ['The pink puffball who inhales his enemies', 'Kirby'],
    ]),
    cat('Consoles', [
      ['Sony\'s console line, currently on its fifth model', 'PlayStation'],
      ['Microsoft\'s home console brand', 'Xbox'],
      ['Nintendo\'s 2017 handheld-console hybrid', 'Switch'],
      ['Sega\'s 16-bit console, called the Genesis in the US', 'Genesis'],
      ['The best-selling home console of all time', 'PlayStation 2'],
    ]),
    cat('Blockbusters', [
      ['The block-building sandbox game by Mojang', 'Minecraft'],
      ['Epic\'s battle royale famous for building and dances', 'Fortnite'],
      ['Rockstar\'s open-world crime series, abbreviated GTA', 'Grand Theft Auto'],
      ['The 2017 open-world Zelda subtitled "Breath of the ___"', 'Wild'],
      ['Capcom\'s long-running survival horror franchise', 'Resident Evil'],
    ]),
    cat('Retro', [
      ['The arcade game with a yellow character eating pellets', 'Pac-Man'],
      ['The falling-blocks puzzle game from the Soviet Union', 'Tetris'],
      ['The ape who hurls barrels at Mario', 'Donkey Kong'],
      ['The 1972 Atari game that simulates table tennis', 'Pong'],
      ['The 1978 arcade shooter about defending Earth from aliens', 'Space Invaders'],
    ]),
    cat('Characters', [
      ['Sega\'s blue, super-fast hedgehog', 'Sonic'],
      ['Treasure hunter Lara Croft stars in this series', 'Tomb Raider'],
      ['The green-armored Master Chief leads this series', 'Halo'],
      ['Mario\'s spiky-shelled archenemy', 'Bowser'],
      ['The Spartan warrior hero of God of War', 'Kratos'],
    ]),
    cat('Esports', [
      ['Riot\'s hit MOBA, "League of ___"', 'Legends'],
      ['Valve\'s tactical shooter series, "Counter-___"', 'Strike'],
      ['Valve\'s MOBA with an annual tournament called The International', 'Dota 2'],
      ['Riot\'s 2020 tactical shooter', 'Valorant'],
      ['Respawn\'s battle royale set in the Titanfall universe', 'Apex Legends'],
    ]),
  ]),

  board('Literature', [
    cat('Shakespeare', [
      ['The young lovers of fair Verona', 'Romeo and Juliet'],
      ['The Danish prince who ponders "To be or not to be"', 'Hamlet'],
      ['The Scottish play about a murderous king', 'Macbeth'],
      ['The Moor of Venice deceived by Iago', 'Othello'],
      ['The London theatre most associated with Shakespeare', 'The Globe'],
    ]),
    cat('Classic Novels', [
      ['Herman Melville\'s novel about a white whale', 'Moby-Dick'],
      ['Jane Austen novel featuring Elizabeth Bennet and Mr. Darcy', 'Pride and Prejudice'],
      ['George Orwell\'s dystopia ruled by Big Brother', '1984'],
      ['F. Scott Fitzgerald\'s novel about Jay Gatsby', 'The Great Gatsby'],
      ['Tolstoy\'s epic novel of Russia and Napoleon', 'War and Peace'],
    ]),
    cat('Kids\' Books', [
      ['The boy wizard created by J.K. Rowling', 'Harry Potter'],
      ['Author of "The Very Hungry Caterpillar"', 'Eric Carle'],
      ['Tolkien novel in which Bilbo Baggins finds a ring', 'The Hobbit'],
      ['In the Narnia title, "The Lion, the Witch and the ___"', 'Wardrobe'],
      ['Pen name of the author of "The Cat in the Hat"', 'Dr. Seuss'],
    ]),
    cat('Poets', [
      ['Author of the poem "The Raven"', 'Edgar Allan Poe'],
      ['"The Road Not Taken" was written by this American poet', 'Robert Frost'],
      ['American poet of "Leaves of Grass"', 'Walt Whitman'],
      ['The reclusive poet from Amherst, Massachusetts', 'Emily Dickinson'],
      ['Chilean Nobel poet who wrote love sonnets', 'Pablo Neruda'],
    ]),
    cat('Detectives', [
      ['Arthur Conan Doyle\'s pipe-smoking sleuth', 'Sherlock Holmes'],
      ['Agatha Christie\'s mustachioed Belgian detective', 'Hercule Poirot'],
      ['Christie\'s elderly amateur sleuth from St. Mary Mead', 'Miss Marple'],
      ['Raymond Chandler\'s hard-boiled detective', 'Philip Marlowe'],
      ['Sherlock Holmes\'s loyal doctor friend', 'Dr. Watson'],
    ]),
    cat('First Lines', [
      ['"Call me Ishmael" opens this novel', 'Moby-Dick'],
      ['"It was the best of times..." begins this Dickens novel', 'A Tale of Two Cities'],
      ['"...the clocks were striking thirteen" opens this novel', '1984'],
      ['"Happy families are all alike..." opens this Tolstoy novel', 'Anna Karenina'],
      ['"In a hole in the ground there lived a ___"', 'Hobbit'],
    ]),
  ]),

  board('Food & Drink', [
    cat('Cuisines', [
      ['Pizza and pasta originated in this country', 'Italy'],
      ['Sushi and ramen come from this country', 'Japan'],
      ['Tacos and enchiladas come from this country', 'Mexico'],
      ['Curry and naan are strongly associated with this country', 'India'],
      ['Croissants and baguettes come from this country', 'France'],
    ]),
    cat('Fruits & Veg', [
      ['A long, yellow, curved fruit', 'Banana'],
      ['The fruit said to keep the doctor away', 'Apple'],
      ['The orange root vegetable said to help eyesight', 'Carrot'],
      ['The fruit fermented to make wine', 'Grape'],
      ['The green fruit that is the base of guacamole', 'Avocado'],
    ]),
    cat('In the Kitchen', [
      ['The appliance you bake bread and cakes in', 'Oven'],
      ['A chef\'s tall, pleated white hat', 'Toque'],
      ['Cooking food by submerging it in hot oil', 'Frying'],
      ['Pasta cooked "al ___" is firm to the bite', 'Dente'],
      ['The French mother sauce of butter, flour, and milk', 'Bechamel'],
    ]),
    cat('Drinks', [
      ['The world\'s most popular drink after water', 'Tea'],
      ['The beverage brewed from roasted beans', 'Coffee'],
      ['True Champagne comes only from this region of France', 'Champagne'],
      ['The Japanese rice wine', 'Sake'],
      ['The agave-based spirit from Mexico', 'Tequila'],
    ]),
    cat('Desserts', [
      ['The frozen dairy treat often served in a cone', 'Ice cream'],
      ['The Italian frozen dessert, denser than ice cream', 'Gelato'],
      ['The Italian layered dessert flavored with coffee', 'Tiramisu'],
      ['The French custard topped with hard caramelized sugar', 'Creme brulee'],
      ['The Austrian pastry made with thin dough and apples', 'Strudel'],
    ]),
    cat('Spices', [
      ['This pepper-derived spice makes food hot', 'Chili'],
      ['This spice from tree bark flavors rolls and lattes', 'Cinnamon'],
      ['The world\'s most expensive spice by weight', 'Saffron'],
      ['The spice that gives curry powder its yellow color', 'Turmeric'],
      ['The fragrant pods used in chai and Indian sweets', 'Cardamom'],
    ]),
  ]),

  board('Space & Astronomy', [
    cat('The Solar System', [
      ['The star at the center of our solar system', 'Sun'],
      ['The planet we live on', 'Earth'],
      ['The largest planet in the solar system', 'Jupiter'],
      ['The planet best known for its spectacular rings', 'Saturn'],
      ['The dwarf planet reclassified in 2006', 'Pluto'],
    ]),
    cat('The Moon', [
      ['The number of natural moons Earth has', '1'],
      ['The first person to walk on the moon', 'Neil Armstrong'],
      ['The NASA program that first landed humans on the moon', 'Apollo'],
      ['The moon\'s dark plains are "maria," Latin for this', 'Seas'],
      ['The moon\'s gravity is the main cause of these ocean movements', 'Tides'],
    ]),
    cat('Stars & Galaxies', [
      ['Our galaxy is called the ___ Way', 'Milky'],
      ['The violent explosion of a dying massive star', 'Supernova'],
      ['The closest star to the Sun', 'Proxima Centauri'],
      ['A region where gravity is so strong not even light escapes', 'Black hole'],
      ['The constellation depicting a hunter with a famous belt', 'Orion'],
    ]),
    cat('Exploration', [
      ['The US space agency', 'NASA'],
      ['NASA\'s reusable spacecraft retired in 2011', 'Space Shuttle'],
      ['The first artificial satellite, launched by the USSR', 'Sputnik'],
      ['The space telescope launched in 1990', 'Hubble'],
      ['The NASA rover that landed on Mars in 2021', 'Perseverance'],
    ]),
    cat('The Planets', [
      ['The "Red Planet"', 'Mars'],
      ['The planet closest to the Sun', 'Mercury'],
      ['The hottest planet in the solar system', 'Venus'],
      ['The planet that rotates tipped on its side', 'Uranus'],
      ['The farthest major planet from the Sun', 'Neptune'],
    ]),
    cat('Cosmic Terms', [
      ['The leading theory of the universe\'s origin, the "Big ___"', 'Bang'],
      ['A rocky body orbiting the Sun, many between Mars and Jupiter', 'Asteroid'],
      ['A "shooting star" streaking through the atmosphere', 'Meteor'],
      ['An icy body with a glowing tail, like Halley\'s', 'Comet'],
      ['The force that keeps planets in orbit around the Sun', 'Gravity'],
    ]),
  ]),

  board('Animals', [
    cat('Mammals', [
      ['The largest living land animal', 'Elephant'],
      ['The tallest animal in the world', 'Giraffe'],
      ['The fastest land animal', 'Cheetah'],
      ['The only mammals capable of true flight', 'Bats'],
      ['The largest animal that has ever lived', 'Blue whale'],
    ]),
    cat('Birds', [
      ['The flightless bird that lays the largest egg', 'Ostrich'],
      ['The national bird of the United States', 'Bald eagle'],
      ['The colorful bird famous for mimicking human speech', 'Parrot'],
      ['The flightless Antarctic bird that swims', 'Penguin'],
      ['The only bird that can fly backward', 'Hummingbird'],
    ]),
    cat('Ocean Life', [
      ['The largest fish, a gentle filter feeder', 'Whale shark'],
      ['The eight-armed sea creature', 'Octopus'],
      ['The toothy predator that terrorized swimmers in "Jaws"', 'Shark'],
      ['The intelligent marine mammal that uses echolocation', 'Dolphin'],
      ['The five-armed sea creature that can regrow lost arms', 'Starfish'],
    ]),
    cat('Bugs', [
      ['The insect that makes honey', 'Bee'],
      ['The winged insect a caterpillar transforms into', 'Butterfly'],
      ['These social insects build hills and march in lines', 'Ants'],
      ['The beetle that glows in the dark on summer nights', 'Firefly'],
      ['The loud summer insect that emerges in broods', 'Cicada'],
    ]),
    cat('Reptiles', [
      ['The reptile that carries a protective shell', 'Turtle'],
      ['The lizard famous for changing color', 'Chameleon'],
      ['The largest living reptile', 'Saltwater crocodile'],
      ['The venomous snake that spreads a hood when threatened', 'Cobra'],
      ['The largest lizard, native to Indonesia', 'Komodo dragon'],
    ]),
    cat('Animal Groups', [
      ['A group of lions', 'Pride'],
      ['A group of wolves', 'Pack'],
      ['A group of crows', 'Murder'],
      ['A group of fish', 'School'],
      ['A group of geese flying in formation', 'Skein'],
    ]),
  ]),

  board('Internet & Memes', [
    cat('Memes 101', [
      ['The "Doge" meme features this dog breed', 'Shiba Inu'],
      ['A link that surprises you with this Rick Astley song is a "rickroll"', 'Never Gonna Give You Up'],
      ['In the "This Is Fine" meme, this animal sits in a burning room', 'Dog'],
      ['The meme of a man turning to look at another woman is called "Distracted ___"', 'Boyfriend'],
      ['Grumpy Cat\'s actual name', 'Tardar Sauce'],
    ]),
    cat('Social Media', [
      ['The photo-sharing app owned by Meta, home of Reels', 'Instagram'],
      ['Twitter was rebranded to this single letter', 'X'],
      ['The short-video app owned by ByteDance', 'TikTok'],
      ['The site organized into subreddits where you earn karma', 'Reddit'],
      ['The professional network owned by Microsoft', 'LinkedIn'],
    ]),
    cat('Emoji Decode', [
      ['🎂 stands for this yearly celebration', 'Birthday'],
      ['🐐 in sports slang stands for this', 'Greatest Of All Time'],
      ['💀 online usually means you are this from laughing', 'Dead'],
      ['🔥 as a compliment means something is this', 'Hot'],
      ['🧢 in slang accuses someone of doing this', 'Lying'],
    ]),
    cat('Internet History', [
      ['"WWW" stands for this', 'World Wide Web'],
      ['This search giant\'s name comes from a misspelled enormous number', 'Google'],
      ['The 1990s dial-up service famous for "You\'ve Got Mail"', 'AOL'],
      ['Founded in 2005 and bought by Google, this is the top video site', 'YouTube'],
      ['The first word sent over ARPANET was meant to be this', 'LOGIN'],
    ]),
    cat('Creators & Streamers', [
      ['The Amazon-owned live streaming platform', 'Twitch'],
      ['YouTuber known for massive giveaways and a burger chain', 'MrBeast'],
      ['The Swedish YouTuber long the most-subscribed individual', 'PewDiePie'],
      ['Viewers paying monthly to support a streamer are these', 'Subscribers'],
      ['A streamer\'s recorded past broadcast, in three letters', 'VOD'],
    ]),
    cat('Chat Acronyms', [
      ['LOL', 'Laughing Out Loud'],
      ['FOMO', 'Fear Of Missing Out'],
      ['IRL', 'In Real Life'],
      ['TL;DR', "Too Long; Didn't Read"],
      ['AFK', 'Away From Keyboard'],
    ]),
  ]),

  board('Superheroes', [
    cat('Marvel', [
      ['The armored genius played by Robert Downey Jr.', 'Iron Man'],
      ['The super-soldier who carries a vibranium shield', 'Captain America'],
      ['This hero was bitten by a radioactive spider', 'Spider-Man'],
      ['The god of thunder who wields Mjolnir', 'Thor'],
      ['The king of Wakanda', 'Black Panther'],
    ]),
    cat('DC', [
      ['The Dark Knight who protects Gotham', 'Batman'],
      ['The Kryptonian in red and blue', 'Superman'],
      ['The Amazon princess with the Lasso of Truth', 'Wonder Woman'],
      ['The scarlet speedster, the fastest man alive', 'The Flash'],
      ['Batman\'s clown-faced archenemy', 'The Joker'],
    ]),
    cat('Secret Identities', [
      ['Clark Kent', 'Superman'],
      ['Bruce Wayne', 'Batman'],
      ['Peter Parker', 'Spider-Man'],
      ['Diana Prince', 'Wonder Woman'],
      ['Bruce Banner', 'The Hulk'],
    ]),
    cat('Superpowers', [
      ['Superman\'s eyes can fire this burning beam', 'Heat vision'],
      ['Wolverine\'s claws are coated in this fictional metal', 'Adamantium'],
      ['Professor X leads the X-Men using this mental power', 'Telepathy'],
      ['The Invisible Woman\'s namesake ability', 'Invisibility'],
      ['A Green Lantern\'s power comes from this worn object', 'Ring'],
    ]),
    cat('Teams', [
      ['Batman\'s youthful partner', 'Robin'],
      ['Marvel\'s team of Iron Man, Thor, and Captain America', 'The Avengers'],
      ['DC\'s team led by Superman and Batman', 'Justice League'],
      ['The team of mutants founded by Charles Xavier', 'X-Men'],
      ['The space team including Star-Lord and Groot', 'Guardians of the Galaxy'],
    ]),
    cat('Villains', [
      ['Spider-Man\'s glider-riding, green-masked foe', 'Green Goblin'],
      ['The purple Titan who collects the Infinity Stones', 'Thanos'],
      ['Superman\'s bald billionaire nemesis', 'Lex Luthor'],
      ['Thor\'s adopted trickster brother', 'Loki'],
      ['The X-Men foe who controls magnetism', 'Magneto'],
    ]),
  ]),

  board('Mythology & Legends', [
    cat('Greek Gods', [
      ['King of the gods, hurler of lightning bolts', 'Zeus'],
      ['God of the sea, brother of Zeus', 'Poseidon'],
      ['Goddess of wisdom, born from Zeus\'s head', 'Athena'],
      ['God who rules the underworld', 'Hades'],
      ['The messenger god with winged sandals', 'Hermes'],
    ]),
    cat('Norse Myth', [
      ['The hammer-wielding god of thunder', 'Thor'],
      ['The one-eyed All-Father', 'Odin'],
      ['The shape-shifting trickster god', 'Loki'],
      ['The great hall where slain warriors feast', 'Valhalla'],
      ['The Norse apocalypse', 'Ragnarok'],
    ]),
    cat('Egyptian Myth', [
      ['The Egyptian sun god', 'Ra'],
      ['The jackal-headed god of mummification', 'Anubis'],
      ['The green-skinned god of the afterlife', 'Osiris'],
      ['The falcon-headed sky god', 'Horus'],
      ['The looped cross symbolizing life', 'Ankh'],
    ]),
    cat('Monsters', [
      ['The bull-headed beast at the center of the labyrinth', 'Minotaur'],
      ['Her gaze turns onlookers to stone', 'Medusa'],
      ['The many-headed serpent slain by Hercules', 'Hydra'],
      ['The one-eyed giant of Greek myth', 'Cyclops'],
      ['Part lion, part goat, part serpent', 'Chimera'],
    ]),
    cat('Heroes & Quests', [
      ['The hero of Homer\'s Odyssey', 'Odysseus'],
      ['He completed twelve legendary labors', 'Hercules'],
      ['He beheaded Medusa', 'Perseus'],
      ['He led the Argonauts after the Golden Fleece', 'Jason'],
      ['This Trojan War hero had one vulnerable heel', 'Achilles'],
    ]),
    cat('Legends & Folklore', [
      ['He pulled the sword from the stone', 'King Arthur'],
      ['The wizard who advised Camelot', 'Merlin'],
      ['The outlaw of Sherwood Forest', 'Robin Hood'],
      ['The monster said to lurk in a Scottish lake', 'Loch Ness Monster'],
      ['The ape-like creature of Himalayan legend', 'Yeti'],
    ]),
  ]),

  board('Wordplay', [
    cat('Anagrams', [
      ['Rearrange LISTEN for this word meaning quiet', 'Silent'],
      ['Rearrange EARTH for this vital organ', 'Heart'],
      ['Rearrange DUSTY for what you do before an exam', 'Study'],
      ['Rearrange ANGERED for this explosive', 'Grenade'],
      ['Rearrange CATERED for this word meaning made', 'Created'],
    ]),
    cat('Palindromes', [
      ['A paddled boat that reads the same backward', 'Kayak'],
      ['Midday, and the same in reverse', 'Noon'],
      ['A vehicle built for speed, spelled the same both ways', 'Racecar'],
      ['The Swedish pop group whose name is a palindrome', 'ABBA'],
      ['A good deed, and a palindrome too', 'Deed'],
    ]),
    cat('Rhyme Time', [
      ['An overweight feline', 'Fat cat'],
      ['A comical rabbit', 'Funny bunny'],
      ['A wealthy sorceress', 'Rich witch'],
      ['An unhappy father', 'Sad dad'],
      ['A chilly swimming spot', 'Cool pool'],
    ]),
    cat('Portmanteaus', [
      ['Breakfast + lunch', 'Brunch'],
      ['Smoke + fog', 'Smog'],
      ['Motor + hotel', 'Motel'],
      ['Web + log', 'Blog'],
      ['Spoon + fork', 'Spork'],
    ]),
    cat('Compound Words', [
      ['Sun + flower', 'Sunflower'],
      ['Rain + bow', 'Rainbow'],
      ['Butter + fly', 'Butterfly'],
      ['Basket + ball', 'Basketball'],
      ['Light + house', 'Lighthouse'],
    ]),
    cat('Hidden Letters', [
      ['The only letter that appears in no US state name', 'Q'],
      ['The most commonly used letter in English', 'E'],
      ['The number of letters in the English alphabet', '26'],
      ['A word using every letter of the alphabet is called this', 'Pangram'],
      ['A sentence reading the same forward and backward is this', 'Palindrome'],
    ]),
  ]),

  board('90s & 2000s Nostalgia', [
    cat('Toys & Fads', [
      ['The keychain virtual pet you had to feed', 'Tamagotchi'],
      ['The bean-filled plush toys collectors hoarded', 'Beanie Babies'],
      ['The cardboard caps you flipped with a slammer', 'Pogs'],
      ['The wheeled sneakers kids rolled down hallways in', 'Heelys'],
      ['The furry robotic pet released in 1998', 'Furby'],
    ]),
    cat('90s TV', [
      ['The Nickelodeon sponge living in a pineapple', 'SpongeBob SquarePants'],
      ['Six friends and a Manhattan coffee shop', 'Friends'],
      ['Sarah Michelle Gellar played this vampire slayer', 'Buffy'],
      ['The "show about nothing" with Jerry and George', 'Seinfeld'],
      ['The Nickelodeon cartoon about Tommy Pickles and friends', 'Rugrats'],
    ]),
    cat('Boy Bands & Pop', [
      ['The band behind "I Want It That Way"', 'Backstreet Boys'],
      ['The girl group that preached Girl Power', 'Spice Girls'],
      ['Britney Spears\'s 1998 debut single', '...Baby One More Time'],
      ['The Nirvana album with a baby on the cover', 'Nevermind'],
      ['The boy band that launched Justin Timberlake', 'NSYNC'],
    ]),
    cat('Old Tech', [
      ['Apple\'s 2001 portable music player', 'iPod'],
      ['The AOL chat program with buddy lists and away messages', 'AIM'],
      ['A standard floppy disk held this many megabytes', '1.44'],
      ['The social network where Tom was everyone\'s first friend', 'MySpace'],
      ['The screeching device that connected you to dial-up', 'Modem'],
    ]),
    cat('Blockbusters', [
      ['The 1993 Spielberg film about a dinosaur park', 'Jurassic Park'],
      ['He declared himself "king of the world" in 1997', 'Leonardo DiCaprio'],
      ['The 1999 film that introduced bullet time', 'The Matrix'],
      ['The 2001 animated film about a green ogre', 'Shrek'],
      ['The 1995 film that was the first fully computer-animated feature', 'Toy Story'],
    ]),
    cat('Video Game Nostalgia', [
      ['The gray Nintendo handheld of 1989', 'Game Boy'],
      ['Sega\'s speedy blue mascot', 'Sonic'],
      ['The 1996 games that started a "gotta catch \'em all" craze', 'Pokemon'],
      ['The N64 shooter based on a Bond film', 'GoldenEye 007'],
      ['The PlayStation racing game with karts and bananas is Mario Kart, but this Sony platformer starred a bandicoot', 'Crash Bandicoot'],
    ]),
  ]),

  board('Cartoons & Anime', [
    cat('Classic Cartoons', [
      ['The rabbit who asks "What\'s up, Doc?"', 'Bugs Bunny'],
      ['Disney\'s mouse mascot', 'Mickey Mouse'],
      ['The cat and mouse locked in eternal chase', 'Tom and Jerry'],
      ['The Great Dane who solves mysteries in a van', 'Scooby-Doo'],
      ['The coyote forever chasing the Road Runner', 'Wile E. Coyote'],
    ]),
    cat('Animated Sitcoms', [
      ['The Simpsons live in this town', 'Springfield'],
      ['Homer Simpson\'s signature exclamation', "D'oh"],
      ['The animated series centered on Peter Griffin', 'Family Guy'],
      ['The Colorado town of Stan, Kyle, Cartman, and Kenny', 'South Park'],
      ['The Simpsons\' bartender', 'Moe'],
    ]),
    cat('Anime Classics', [
      ['The ninja with the Nine-Tailed Fox sealed inside him', 'Naruto'],
      ['The straw-hat-wearing pirate captain of One Piece', 'Monkey D. Luffy'],
      ['The Saiyan hero of Dragon Ball', 'Goku'],
      ['The series about humanity hiding behind walls from giants', 'Attack on Titan'],
      ['In Death Note, this student writes names in a killer notebook', 'Light Yagami'],
    ]),
    cat('Studio Ghibli', [
      ['The big-bellied forest spirit with a huge grin', 'Totoro'],
      ['The film about a girl working in a spirit bathhouse', 'Spirited Away'],
      ['The young witch who runs a delivery service', 'Kiki'],
      ['This wizard owns a famous moving castle', 'Howl'],
      ['The legendary director who co-founded Studio Ghibli', 'Hayao Miyazaki'],
    ]),
    cat('Pokemon', [
      ['The electric mouse mascot of the franchise', 'Pikachu'],
      ['The device used to catch Pokemon', 'Poke Ball'],
      ['The fire-type starter of the Kanto region', 'Charmander'],
      ['The legendary bird of ice', 'Articuno'],
      ['Number 001 in the National Pokedex', 'Bulbasaur'],
    ]),
    cat('Catchphrases', [
      ['"I\'m ready!" is chanted by this sea sponge', 'SpongeBob'],
      ['"Yabba dabba doo!"', 'Fred Flintstone'],
      ['"That\'s all folks!" closes these cartoons', 'Looney Tunes'],
      ['"Cowabunga!" is the cry of these reptiles', 'Teenage Mutant Ninja Turtles'],
      ['"To infinity and beyond!"', 'Buzz Lightyear'],
    ]),
  ]),

  board('Weird & Wonderful', [
    cat('Superlatives', [
      ['The tallest building in the world, found in Dubai', 'Burj Khalifa'],
      ['The largest mammal on Earth', 'Blue whale'],
      ['The language with the most native speakers', 'Mandarin Chinese'],
      ['The most visited art museum in the world', 'The Louvre'],
      ['Often called the oldest continuously inhabited city, it is Syria\'s capital', 'Damascus'],
    ]),
    cat('Phobias', [
      ['Fear of spiders', 'Arachnophobia'],
      ['Fear of heights', 'Acrophobia'],
      ['Fear of enclosed spaces', 'Claustrophobia'],
      ['Fear of open or crowded places', 'Agoraphobia'],
      ['Fear of the number 13', 'Triskaidekaphobia'],
    ]),
    cat('Body Oddities', [
      ['The number of hearts an octopus has', '3'],
      ['Adults normally have this many teeth', '32'],
      ['Hair and fingernails are made mostly of this protein', 'Keratin'],
      ['This part of the eye has no blood supply', 'Cornea'],
      ['The medical term for the funny bone nerve', 'Ulnar nerve'],
    ]),
    cat('Flags & Colors', [
      ['The three colors of the French flag', 'Blue, white, and red'],
      ['This country\'s flag bears a red maple leaf', 'Canada'],
      ['The only national flag that is not a rectangle', 'Nepal'],
      ['This flag shows a red circle representing the sun', 'Japan'],
      ['This Middle Eastern flag features a cedar tree', 'Lebanon'],
    ]),
    cat('Customs Around the World', [
      ['In Japan you remove these before entering a home', 'Shoes'],
      ['In the UK, India, and Australia, you drive on this side', 'Left'],
      ['The Spanish tradition of an afternoon rest', 'Siesta'],
      ['The Indian greeting made with palms pressed together', 'Namaste'],
      ['This Scandinavian concept means cozy contentment', 'Hygge'],
    ]),
    cat('Random Facts', [
      ['The number of sides on a stop sign', '8'],
      ['The number of squares on a chessboard', '64'],
      ['The number of keys on a standard piano', '88'],
      ['A group of unicorns is called this', 'Blessing'],
      ['Honey found in ancient tombs was still this', 'Edible'],
    ]),
  ]),

  board('Pop Culture Grab Bag', [
    cat('Reality TV', [
      ['The kitchen competition hosted by Gordon Ramsay', "Hell's Kitchen"],
      ['The dating show that ends with a final rose', 'The Bachelor'],
      ['Castaways vote each other off in this competition', 'Survivor'],
      ['The singing competition with spinning chairs', 'The Voice'],
      ['The series that made the Kardashian family famous', 'Keeping Up with the Kardashians'],
    ]),
    cat('Board Games', [
      ['The game where you buy Boardwalk and build hotels', 'Monopoly'],
      ['The word game played with lettered tiles', 'Scrabble'],
      ['The mystery game featuring Colonel Mustard', 'Clue'],
      ['The game of trading sheep, wheat, and building settlements', 'Catan'],
      ['The strategy game of global conquest', 'Risk'],
    ]),
    cat('Famous Couples', [
      ['The rapper married to Beyonce', 'Jay-Z'],
      ['"Brangelina" paired Brad Pitt with this actress', 'Angelina Jolie'],
      ['This prince married Meghan Markle', 'Prince Harry'],
      ['"Bennifer" paired Ben Affleck with this singer', 'Jennifer Lopez'],
      ['This Kardashian was married to Kanye West', 'Kim Kardashian'],
    ]),
    cat('Logos & Brands', [
      ['The swoosh belongs to this brand', 'Nike'],
      ['The brand marked by three stripes', 'Adidas'],
      ['The luxury house with interlocking Cs', 'Chanel'],
      ['The clothing brand with a crocodile', 'Lacoste'],
      ['The Italian fashion house using a Medusa head', 'Versace'],
    ]),
    cat('Award Shows', [
      ['The film awards handing out golden statuettes', 'Oscars'],
      ['The music awards with a gramophone trophy', 'Grammys'],
      ['The awards honoring television', 'Emmys'],
      ['The awards honoring Broadway theatre', 'Tonys'],
      ['Winning all four major American entertainment awards makes you this', 'EGOT'],
    ]),
    cat('Fictional Places', [
      ["Harry Potter's school of witchcraft and wizardry", 'Hogwarts'],
      ['The land Dorothy lands in after the tornado', 'Oz'],
      ['The kingdom ruled by Elsa in Frozen', 'Arendelle'],
      ['The continent containing King\'s Landing', 'Westeros'],
      ['The hobbit homeland in Middle-earth', 'The Shire'],
    ]),
  ]),
];
